#!/bin/bash

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINARY_ROOT="${ROOT}/bin"
LIBRARY_ROOT="${ROOT}/lib"

ENVIRONMENT='PATH="${BINARY_ROOT}:${PATH}"'
if [ `uname` == 'Darwin' ]; then
    ENVIRONMENT+=' DYLD_LIBRARY_PATH="${LIBRARY_ROOT}:${DYLD_LIBRARY_PATH}"'
else
    ENVIRONMENT+=' LD_LIBRARY_PATH="${LIBRARY_ROOT}:${LD_LIBRARY_PATH}"'
fi

eval "${ENVIRONMENT} $@"
